PaletteProvider + withPalette
callstack-io/react-native-material-palette pull request #17
Opened 2017-07-13 12:04 UTC by zamotany

TODO:

- [ ] docs
- [ ] tests
- [ ] optimize `withPalette#_mergePaletteWithDefaults`

2017-07-21 16:14 UTC, rgommezz requested changes
I just finished a 1st iteration. Generally speaking, awesome work man, specially with the tests and documentation! 🚀  🚀   Left some comments to address.

2017-07-21 16:14 UTC, rgommezz commented on docs/API.md
> +`withMaterialPalette` is a Higher Order Component (HOC), which allows to seemlessy _connect_ to the `MaterialPaletteProvider` and get the palette instance via context.
The description is not exactly right. More accurate would be: "`withMaterialPalette` is a function that returns a Higher Order Component (HOC)...". You can check it in here: https://facebook.github.io/react/docs/higher-order-components.html

2017-07-21 16:14 UTC, rgommezz commented on README.md
> +## Usage with `MaterialPaletteProvider` and `withMaterialPalette`
As a generic thing, the word "Material" sounds to me a bit repetitive and redundant in those utilities. What do you think of just `PaletteProvider` and `withPalette`? Actually you already named the files like that, but exported the longer names :)

2017-07-21 16:14 UTC, rgommezz commented on src/withPalette.js
> +  mapPaletteToStyle: ?(palette: PaletteInstance) => {
The flow question mark is wrong, should be `mapPaletteToStyle?: (palette: PaletteInstance) => {..`

Also, since the mapper function returns a `StyleSheet`, we could flow type it better like this:

```javascript
import type { StyleObj } from 'react-native/Libraries/StyleSheet/StyleSheetTypes';
...

function withMaterialPalette(
  mapPaletteToStyle: ?(palette: PaletteInstance) => StyleObj,
  localDefaults?: PaletteDefaults
) => (WrappedComponent: ReactClass<*>) => ReactClass<*>;
```

Also, flow definition in the docs should reflect that change.

2017-07-21 16:14 UTC, rgommezz commented on src/withPalette.js
> +    class MaterialPaletteConnector extends Component<void, *, State> {
We need to hoist statics from the `WrapperComponent` to the `MaterialPaletteConnector` (I would even call it PaletteConnector, but that's not relevant), since lots of libraries rely on statics being defined to work properly. For that, we could use https://github.com/mridgway/hoist-non-react-statics.

Instead of returning the `MaterialPaletteConnector` class, we would have to return at the end:

`return hoistStatics(MaterialPaletteConnector, WrappedComponent);`

2017-07-21 16:14 UTC, rgommezz commented on src/PaletteProvider.js
> +          enhancedError.message = `Uncaugth MaterialPaletteProvider exception: ${enhancedError.message}`;
Typo `Uncaught`

2017-07-21 16:14 UTC, rgommezz commented on src/PaletteProvider.js
> +        : <this.props.waitForPalette />;
We'd also need to verify that `this.props.waitForPalette` is a valid React Component. If you pass an object it would break.

Anyway, I am not sure about the usefulness of this prop. We should basically render `null` by default, unless a React component is passed otherwise. I'd advocate for an optional prop called `LoaderComponent` that, if provided, renders the component passed as it waits.

Also, verification that `LoaderComponent` is a React Component is needed. Probably `componentWillMount` is a good place for verifying and throwing if necessary.

2017-07-21 16:14 UTC, rgommezz commented on docs/API.md
> +* `waitForPalette?: boolean | React$Component<*, *, *> | ((...args: *) => React$Element<*>)` (optional) - If specified, while waiting for palette to be created, will render either `null` (if `waitFor
I'd change that for `LoaderComponent`. Even if we don't provide `waitForPalette` it'd render `null`. See my other comment in https://github.com/callstack-io/react-native-material-palette/pull/17/files#diff-a31b107da6db08a17fa6078744ebdafbR120.

2017-07-21 16:14 UTC, rgommezz commented on src/PaletteProvider.js
> +      ...this.context,
No need of spreading the previous `context`

2017-07-21 16:14 UTC, rgommezz commented on docs/API.md
> +* `onFinish?: (palette: PaletteInstance, globalDefaults: PaletteDefaults) => void` - (optional) - Finish handler, called when the palette is created, but before it gets propagated to _connected_ comp
I am curious about when you'd use `onFinish`. I don't understand what you mean by "use it, if you want to mutate the palette instance". What'd be an use case for that?

2017-07-21 16:14 UTC, rgommezz commented on src/withPalette.js
> +        if (typeof this.unsubscribe === 'function') {
I think we don't need this check in `componentWillUnmount`, do we? `componentWillMount` is already making sure `this.unsubscribe` is a function, otherwise it will throw before the component even mounts.

2017-07-21 16:16 UTC, rauliyohmc commented
Btw, I tried to run `flow` and it hangs eternally. Does it happen to you? I even tried with a different version, reinstalled `node_modules` etc...

2017-07-21 16:48 UTC, zamotany commented on docs/API.md
> +* `onFinish?: (palette: PaletteInstance, globalDefaults: PaletteDefaults) => void` - (optional) - Finish handler, called when the palette is created, but before it gets propagated to _connected_ comp
If for some reason, user want to mutate palette, `onFinish` should be used for that. Besides it's an escape hatch for case if someone want to render splash screen and then animate the transision.

2017-07-21 16:51 UTC, zamotany commented on README.md
> +## Usage with `MaterialPaletteProvider` and `withMaterialPalette`
If you're using named import it should tell you exactly what it is and in React devtools you would see a component named `MaterialPaletteProvider`, not `PaletteProivder`, so it's more clear what exactly the component is.

2017-07-21 16:52 UTC, zamotany commented on src/withPalette.js
> +  mapPaletteToStyle: ?(palette: PaletteInstance) => {
It doesn't return StyleSheet, it returns an object.

2017-07-21 16:56 UTC, zamotany commented on src/withPalette.js
> +        if (typeof this.unsubscribe === 'function') {
Flow will cry,

2017-07-21 16:58 UTC, zamotany commented
Nope, it works for me.

2017-07-21 18:22 UTC, rauliyohmc commented on src/withPalette.js
> +  mapPaletteToStyle: ?(palette: PaletteInstance) => {
Right, I somehow wanted to catch wrong properties in that Object with flow for the user, but just skimming the `StyleSheet` library within RN, there are no proper Flow definitions for that. Let's keep it like that then

2017-07-24 08:19 UTC, zamotany commented on src/withPalette.js
> +        if (typeof this.unsubscribe === 'function') {
W/o this check:
```
src/withPalette.js:68
 68:         this.unsubscribe();
             ^^^^^^^^^^^^^^^^^^ call of method `unsubscribe`. Function cannot be called on possibly null value
 68:         this.unsubscribe();
             ^^^^^^^^^^^^^^^^ null

src/withPalette.js:68
 68:         this.unsubscribe();
             ^^^^^^^^^^^^^^^^^^ call of method `unsubscribe`. Function cannot be called on possibly undefined value
 68:         this.unsubscribe();
             ^^^^^^^^^^^^^^^^ undefined
```

2017-07-24 11:08 UTC, rgommezz approved these changes

2017-07-24 11:09 UTC, rauliyohmc commented
LGTM 👍

2017-07-24 11:33 UTC, zamotany commented
Close #17

2017-07-24 11:34 UTC, merged