Default profile colors
callstack-io/react-native-material-palette pull request #27
Opened 2017-07-28 12:31 UTC by rauliyohmc

After sampling some images, I extrapolated some greyscale colors as defaults for each profile.
See https://github.com/callstack-io/react-native-material-palette/issues/2

This PR merges the palette instance with the defaults, before the event emitter publish the change to all subscribers

2017-07-30 11:24 UTC, satya164 approved these changes

2017-07-30 17:48 UTC, zamotany requested changes
Missing PaletteProvider test cases. Minimal CC - 100% 😛

2017-07-30 17:48 UTC, zamotany commented on src/PaletteProvider.js
> +      if (typeof this.props.defaults !== 'object') {
Can you flatten the conditionals?
```
if (this.props.defaults && typeof this.props.defaults !== 'object')
```

2017-07-30 17:48 UTC, zamotany commented on src/PaletteProvider.js
>            this.setState({ palette });
You should pass `paletteWithDefaults` instead of `palette`

2017-07-30 17:48 UTC, zamotany commented on src/PaletteProvider.js
> +      ...Object.keys(palette)
You don't need to spread the object inside object -> you're reducing it to object already.

2017-07-30 17:58 UTC, satya164 commented on src/PaletteProvider.js
> +      ...Object.keys(palette)
@zamotany I think it's because he is merging it with `defaults`

2017-07-31 04:59 UTC, zamotany commented on src/PaletteProvider.js
> +      ...Object.keys(palette)
a ok, haven't seen that `...defaults`

2017-07-31 07:39 UTC, rauliyohmc commented on src/PaletteProvider.js
>            this.setState({ palette });
What do you mean? I am already passing `paletteWithDefaults` to `onFinish`

2017-07-31 07:40 UTC, rauliyohmc commented on src/PaletteProvider.js
> +      if (typeof this.props.defaults !== 'object') {
That part is not finished, I am about to complete the `defaults` validation today

2017-08-01 11:19 UTC, satya164 commented on src/constants/defaults.js
> +export const validColorProfiles = [
You can use an object here and reuse it for the typedef:

```js
const validColorProfiles = {
  vibrant: true,
  lightVibrant: true,
  darkVibrant: true,
  muted: true,
  lightMuted: true,
  darkMuted: true,
};

type ColorProfile = $Keys<typeof validColorProfiles>;
```

2017-08-01 14:19 UTC, satya164 requested changes

2017-08-01 14:19 UTC, satya164 commented on src/utils/validate.js
> +      if (!Object.keys(validColorProfiles).includes(profile)) {
Or `profile in validColorProfiles`

2017-08-02 09:26 UTC, rauliyohmc commented
@satya164 @zamotany you can take another look 🤖

2017-08-02 11:11 UTC, zamotany requested changes

2017-08-02 11:11 UTC, zamotany commented on src/__tests__/createMaterialPalette.test.js
> +    createPalette({
You need to return the Promise from `createPalette` otherwise the test will assume it's sync and won't wait for it.

2017-08-03 12:36 UTC, satya164 commented
You guys are crazy

2017-08-03 12:36 UTC, satya164 approved these changes

2017-08-03 13:01 UTC, zamotany requested changes

2017-08-03 13:01 UTC, zamotany commented on src/utils/__tests__/validateCreatePalette.test.js
> +jest.mock('../validateCreatePaletteArgs', () => ({
`jest.mock('../validateCreatePaletteArgs')` is sufficient

2017-08-03 13:04 UTC, zamotany approved these changes
👍

2017-08-03 13:05 UTC, merged