Feat/app example
callstack-io/react-native-material-palette pull request #30
Opened 2017-08-08 23:38 UTC by rauliyohmc

2017-08-09 23:51 UTC, rauliyohmc commented
@satya164 I don't know how to solve the backwards compatibility with Kotlin, maybe you have some ideas. Apparently the solution works properly in Java. Maybe we can write that boilerplate file in Java and leave the one with the logic with Kotlin?

2017-08-10 07:36 UTC, satya164 commented
I've never really written kotlin, but I'll give it a try today.

2017-08-12 09:51 UTC, satya164 requested changes

2017-08-12 09:51 UTC, satya164 commented on .eslintrc
> +  "parser": "babel-eslint",
We should use `eslint-config-callstack-io` instead

2017-08-12 09:51 UTC, satya164 commented on .flowconfig
> +; Ignore the example app
We shouldn't ignore the example app. Using Flow in examples (and tests) makes sure Flow is not broken for our public API.

2017-08-12 09:51 UTC, satya164 commented on example/package.json
> +    "extends": "../.eslintrc"
It shouldn't be necessary since we don't have any overrides

2017-08-12 14:12 UTC, rauliyohmc commented on .eslintrc
> +  "parser": "babel-eslint",
There is a separate issue for that: https://github.com/callstack-io/react-native-material-palette/issues/29

2017-08-14 00:32 UTC, merged