Minor refactor
callstack-io/react-native-material-palette pull request #35
Opened 2017-08-12 10:53 UTC by satya164

2017-08-12 14:28 UTC, rgommezz requested changes

2017-08-12 14:28 UTC, rauliyohmc commented on src/PaletteProvider.js
> +  LoaderComponent?: ReactClass<*> | ((...args: *) => React.Element<*>),
Let's use `Array<*>` or `Array<any>` better for the rest parameter.

From the docs: `If you add a type annotation to a rest parameter, it must always explicitly be an Array type.`

https://flow.org/en/docs/types/functions/#toc-rest-parameters

2017-08-12 14:28 UTC, rauliyohmc commented on src/PaletteProvider.js
>          this.eventEmitter.publish({
We need to `publish` before setting state, remember the issue we discussed at the office. The change is in my branch anyway, but will be good to have it here as well already 🤖

2017-08-12 14:28 UTC, rauliyohmc commented on src/PaletteProvider.js
> +    if (shouldRender) {
shouldn't we change the order? If `forceRender` is provided, it seems natural for me to override `LoaderComponent`, what do you think?

2017-08-12 14:28 UTC, rauliyohmc commented on src/__tests__/PaletteProvider.test.js
> +          expect(error.message).toMatch(/MaterialPaletteProvider.*test/);
Why not `expect(error.message).toBe('Uncaught MaterialPaletteProvider exception: test')` for more accuracy of what's being thrown?

2017-08-12 14:28 UTC, rauliyohmc commented on src/__tests__/withPalette.test.js
> +      expect(StyleSheet.flatten(style)).toEqual({ fontSize: '14px' });
Nice! Didn't know about `flatten` 👍

2017-08-12 14:43 UTC, rauliyohmc commented
Also, we need to update the API docs to remove `onInit` from there

2017-08-12 15:58 UTC, satya164 commented on src/__tests__/PaletteProvider.test.js
> +          expect(error.message).toMatch(/MaterialPaletteProvider.*test/);
Blame @zamotany xD

2017-08-12 15:59 UTC, satya164 commented on src/PaletteProvider.js
> +    if (shouldRender) {
Just following what's in the comment in the prop types. cc @zamotany

2017-08-12 16:32 UTC, zamotany commented on src/PaletteProvider.js
> +    if (shouldRender) {
From the docs: _Does not take effect if LoaderComponent is specified!_

Besides, why would you specify `LoaderComponent` when you would force the render anyway?

2017-08-12 16:33 UTC, zamotany reviewed
Why are ~we~ you removing `onInit`??

2017-08-12 16:42 UTC, satya164 commented
@zamotany it's basically the same as when the provider mounts, so seems unnecessary

2017-08-13 15:05 UTC, rgommezz approved these changes

2017-08-13 15:06 UTC, merged